server:
  name: "BeiDou-Go"
  host: "0.0.0.0"
  log_file: ""   # 空=输出到终端

database:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  db_name: "beidougo"

login:
  port: 8484
  auto_register: true  # 自动注册新账号（调试阶段开启）

channel:
  port: 7575
  max_players: 100

script:
  path: "scripts"
  hot_reload: false
